edgarj:
  base:
    time_zone_for_timestamp_comparison: '9'
  work_dir: <%= Rails.root + 'tmp/edgarj' %>
  csv_dir:  <%= Rails.root + 'tmp/edgarj/csv_download' %>

  # After creating temporary csv download file, set the permission
  # to the file.  Default is that only owner read+write.
  csv_permission: 0600
  _overwrite_test: 'hello'

  page_info:
    default_lines:      10

  belongs_to:
    # locate popup link to 'field' or 'label' (default = 'field')
    popup_on:           'field'
    link_tag:           '<span class="edgarj_field_belongs_to_button">▼</span>'
    disable_clear_link: false
